---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "muffin-wallet.fullname" . }}
  labels:
    app: {{ .Values.labels.app }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.labels.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}